export const ROLES = Object.freeze({
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  SALESPERSON: 'SALESPERSON',
  DISPATCHER: 'DISPATCHER',
  TECHNICIAN: 'TECHNICIAN',
  ACCOUNTANT: 'ACCOUNTANT',
  STOREKEEPER: 'STOREKEEPER',
  CUSTOMER: 'CUSTOMER',
});
export const ROLE_VALUES = Object.values(ROLES);
export const STAFF_ROLES = ROLE_VALUES.filter((role) => role !== ROLES.CUSTOMER);
export const GLOBAL_BRANCH_ROLES = [ROLES.OWNER, ROLES.ADMIN];
