import { Router } from 'express';
import authRoutes from './authRoutes.js';
import branchRoutes from './branchRoutes.js';
import userRoutes from './userRoutes.js';
import leadRoutes from './leadRoutes.js';
import customerRoutes from './customerRoutes.js';
import inspectionRoutes from './inspectionRoutes.js';
import quotationRoutes from './quotationRoutes.js';
import contractRoutes from './contractRoutes.js';
import visitRoutes from './visitRoutes.js';
import technicianRoutes from './technicianRoutes.js';
import jobCardRoutes from './jobCardRoutes.js';
import inventoryRoutes from './inventoryRoutes.js';
import billingRoutes from './billingRoutes.js';
import complaintRoutes from './complaintRoutes.js';
import hrRoutes from './hrRoutes.js';
import reportRoutes from './reportRoutes.js';
import integrationRoutes from './integrationRoutes.js';
import companyRoutes from './companyRoutes.js';
import activityRoutes from './activityRoutes.js';
import procurementRoutes from './procurementRoutes.js';
import mediaRoutes from './mediaRoutes.js';
import bulkRoutes from './bulkRoutes.js';
import paymentRoutes from './paymentRoutes.js';
import siteConfigRoutes from './siteConfigRoutes.js';
const router = Router();
router.get('/health', (_req, res) =>
  res.json({ status: 'ok', timestamp: new Date().toISOString() }),
);
router.use('/auth', authRoutes);
router.use('/branches', branchRoutes);
router.use('/users', userRoutes);
router.use('/leads', leadRoutes);
router.use('/customers', customerRoutes);
router.use('/inspections', inspectionRoutes);
router.use('/quotations', quotationRoutes);
router.use('/contracts', contractRoutes);
router.use('/visits', visitRoutes);
router.use('/technicians', technicianRoutes);
router.use('/job-cards', jobCardRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/billing', billingRoutes);
router.use('/complaints', complaintRoutes);
router.use('/hr', hrRoutes);
router.use('/reports', reportRoutes);
router.use('/integrations', integrationRoutes);
router.use('/company', companyRoutes);
router.use('/activity', activityRoutes);
router.use('/procurement', procurementRoutes);
router.use('/media', mediaRoutes);
router.use('/bulk', bulkRoutes);
router.use('/payments', paymentRoutes);
router.use('/site-config', siteConfigRoutes);
export default router;
